version: 2.1
orbs:
  node: circleci/node@4.7
commands:
  my-command:
    parameters:
      to:
        type: string
        default: "Dan"
    steps:
      - run: echo "Hello <<parameters.to>>" 
jobs:
  build:
    docker:
      - image: cimg/node:19.6.0
    steps:
      - checkout
      - run:
          name: installing dependencies
          command: npm i --force
      - run: 
          name: installing base
          command: whoami     
      - my-command:
          to: "Dini"
workflows:
  builder:
    jobs:
      - build

    
    
    























# version: 2.1
# orbs:
#   node: circleci/node@4.7
# workflows:
#   sample:
#     jobs:
#       - Testing:
#           version: '16.10'
#           pkg-manager: npm
#           steps:
#             - run:
#                 name: Check Scripts
#                 command: |
#                      npm install --force
