version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:19.6.0
    steps:
      - checkout
      - run:
          name: installing dependencies
          command: npm i --force
      - run: whoami 
             sudo mkdir temp 
             ls 
             echo "successful"
workflows:
  build_dep:
    jobs:
      - build
