version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:19.6.0
    steps:
      - checkout
      - run:
          name: installing dependencies
          command: npm i --force
      - run:
          name: running tests
          command: npm run tests
workflows:
  build_dep:
    jobs:
      - build
