jobs:
  build:
    docker:
      - image: cimg/node:19.5.0
    working_directory: ~/my-app  
    steps:
      - checkout
      - run: ls & pwd
      - run: npm install --force
      - run: echo "The value is <<parameters.dynamo>>"
