version: 2.1
parameters:
  appName:
    type: string
    default: "demoed"
  appType:
    type: string
    default: "docker"
jobs:
  build:
    docker:
      - image: cimg/node:19.6.0
    steps:
      - checkout
      - run:
          name: installing dependencies
          command: npm i --force
      - run: 
          name: installing base
          command: whoami
  post_action:
    docker:
      -image: cimg/node:19.6.0
    steps:
      - run: echo "app Name regular was ${appName}"
      - run: echo "$(pwd) == << pipeline.parameters.appType >>"
workflows:
  builder:
    jobs:
      - post_action
      - build:
          filters:
            branches:
              only:
                - train-cicd
