version: 2.1
jobs:
  builds:
    docker:
      - image: circleci/node:4.8.2
    working_directory: ~/repo  
    steps:
      - checkout
      - run: echo "build success"
  deploy:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo  
    steps:
      - run: pwd & ls

workflows:
  build_and_deploy:
    jobs:
      - builds
      - deploy:
          requires:
            - builds
