version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:19.6.0
    steps:
      - checkout
      - run: ls 
      - run: echo " node version is" node --version
      
 workflows:
   build_dep:
     jobs:
       - build
