version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:19.6.0
    steps:
      - checkout
      - run:
          name: installing dependencies
          command: npm i --force
      - run: 
          name: installing base
          command: whoami
workflows:
  build_dep:
    jobs:
      - build
          filters:
            branches:
              - only: train-cicd
